### ISSUE TITLE
Can vico work with image-to-video?

### ISSUE THREAD

**Issue by teplov-andrew** [Adamdad/vico#3]
Hello, thanks for this amazing work. Can vico work with image-to-video? Will the code be developed for i2v?

**Comment by Adamdad** [comment]
In general, yes, as long as the image is input to the model through cross-attention. However, for some image-to-video models, the condition is added to the model in additional ways beyond cross-attention. For example, Stable Video Diffusion concatenates the image to the latent code as input to the diffusion Unet. I am still working on addressing this issue.

The T2V model provides a simpler scenario because text conditions are typically (in most models) added through cross-attention. That is why I focus on T2V in my paper.
